### ISSUE TITLE
pcfdev 0.18.0 help

### ISSUE THREAD

**Issue by shouah** [vmware-archive/pcfdev#112]
I opened a support ticket with Pivotal about these questions but was told the "commercial" version of pcfdev is not supported by Pivotal so I'm resorting at posting here:

1) will there be support for using the CLI plugin with a different virtualization provider than virtualbox? in the earlier release where vagrant was used then we had the option to use the 'vagrant plugin for vmware' to deploy pcfdev to VMware Workstation but not anymore with the CLI plugin because 'cf dev start' result in 'Error: could not find VBoxManage executable'.
background: our corporate security does not allow the use of virtualbox so we had to manually make pcfdev works within vmware workstation.

2) can you outline the Ubuntu commands used to start and stop pcfdev?
2.a) I believe that the "cf dev start" approximately launches pcfdev using the "/var/pcfdev/run" script
2.b) I am not sure about the "cf dev stop" - it seems that issuing "monit stop all" isn't sufficient because there are processes still running after monit indicates all the services are stopped. those processes weren't there before the start sequence.

3) the following changes do not appear to persist between stop and start of pcfdev using the manual scripts:
3.a) change to the password for the 'admin' userid keeps getting reset back to 'admin' -- however change to the password for the 'user' persists.
3.b) uploading updated buildpacks get reverted back to the original that ships with pcfdev following the restart.
-> how do I make these 2 changes persist across pcfdev stop/start?

**Comment by sclevine** [comment]
Hi @shouah,

Sorry for the confusion! We will follow up with you soon.

**Comment by sclevine** [comment]
Hi @shouah,

In a few early releases of PCF Dev, it was possible to modify the provided start scripts to boot a VMware Workstation VM that we were using internally for CI. As VMware Workstation/Fusion and the Vagrant VMware plugin require licensing, and due to a lack of interest in PCF Dev in these platforms, official support is not on the roadmap. The next platforms that will likely be supported are vSphere and AWS. If you have support from Pivotal for PCF, don't hesitate to talk with your sales representative about your requirements.

I am happy to describe what the CLI plugin does with the OVA in Virtualbox, but the OVA isn't been tested in VMware, and may not work. The `cf dev start` command first configures two network interfaces (that aren't specified in the OVA metadata). The first is a NAT interface, and the second is a host-only interface. They must be configured via the virtualizer and inside the VM. The host-only interface must have an IP that matches the system domain (ex. `192.168.11.11` / `local.pcfdev.io`). Then the `/var/pcfdev/run` script is run with the system domain, host-only IP, and requested services as arguments.

To stop the VM, an ACPI power-off event is issued that is picked up by the OS.

That said, I wouldn't recommend manually managing the VM. The cf CLI plugin is robust and handles many different VM states and error conditions. If you are able to get the OVA working in VM, the user experience may not be satisfactory.

We currently don't support changing the admin password, but we will look into buildpacks getting reset between VM reboots. For now, suspending the VM instead of stopping it may allow you to work around these restrictions.

Hope this is helpful,
Stephen

**Comment by shouah** [comment]
Thank you: that's a lot more answer than I ever received, especially from the paid support.

The two NIC info was the missing detail that allowed me to re-use the public "local.pcfdev.io" wildcard DNS.

I can't seem to find the UAA admin and BOSH director credentials, nor the correct URL for those CF components -- are they exposed or available with pcf-dev?
- I tried "uaac target uaa.local.pcfdev.io" followed by "uaac token get client get admin -s admin" but got "unauthorized / bad credentials".
- I tried "bosh target local.pcfdev.io:2555" but there doesn't seem to be any bosh there.

Do UAAC and BOSH CLI work against pcf-dev?

**Comment by sclevine** [comment]
Hi @shouah,

The proprietary distribution of PCF Dev is considered a [beta product](https://network.pivotal.io/legal_documents/pivotal_beta_eula), and while we don't currently provide support for it the way we provide support for PCF, I am happy to answer questions here. Sorry if this was confusing. I will follow up with our support team.

There is no BOSH director in PCF Dev. You can't deploy BOSH releases or OpsManager tiles to it. This keeps the VM small and the boot time quick. We may include an empty BOSH director eventually, but likely not in the near-term.

UAA, however, is available. The admin secret should be `admin-client-secret`. You can view the full manifest that's used to deploy the OSS components of PCF Dev here: https://github.com/pivotal-cf/pcfdev/blob/master/images/manifest.yml

**Comment by shouah** [comment]
thank you. I believe this is most of what I need to finally get up and running with pcf-dev (within our corporate constraints)
