### ISSUE TITLE
unable to download PCF Dev

### ISSUE THREAD

**Issue by alekranthi** [vmware-archive/pcfdev#123]
unable to download PCF Dev, it display a popup with below message while downloading PCF Dev for windows 10 64 bit desktop

Unfortunately, we are unable to provide you with access to download software at this time. Please contact export@pivotal.io for assistance.

can anyone please help me proceed with this ?

**Comment by mdelillo** [comment]
Hi @alekranthi, this is an issue with your account on Pivotal Network and is unrelated to PCF Dev (you'll get the same error if you try to download any software from the site). There's some automatic screening that happens when you register and it looks like your account got flagged. You'll need to email export@pivotal.io and have them override it. Then you should be able to download PCF Dev.

**Comment by alekranthi** [comment]
Thank you @mdelillo
