### ISSUE TITLE
cf logs : Error dialing traffic controller server

### ISSUE THREAD

**Issue by sunilkcs** [vmware-archive/pcfdev#127]
I am getting below error when i try to see the logs of my app. I am getting the same error when do 'cf push' also (My instance is running successfully even  though i am getting this error). I am behind a corporate proxy. What i should do for this ? Its working perfectly from home. Kindly help. Thank You.

```
C:\Users\588807>cf logs myprojectname
FAILED
Error dialing traffic controller server: dial tcp 54.85.105.67:443: connectex: No connection could be made because the target
 machine actively refused it..
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.run.pivotal.i
o:443).
```

**Comment by aemengo** [comment]
@sunilkcs Did you by chance start PCF Dev here using the CLI? The IP listed there suggests otherwise. If it works at home, but not at work, we can only assume that your proxy is forbidding outbound connections to that machine.  If you need a PCF Dev, we'd much rather you use the CLI on your local workstation. [http://docs.pivotal.io/pcf-dev/index.html](http://docs.pivotal.io/pcf-dev/index.html)

**Comment by sclevine** [comment]
@sunilkcs You do not have PCF Dev targeted. Please run the `cf login` command output by `cf dev start`.

**Comment by sunilkcs** [comment]
Well. I am not getting any more error after allowing this traffic in doppler.run.pivotal.io:443. It was outbound connection problem as Aemengo mentioned. Thank You all for the reply
