### ISSUE TITLE
Not able to login into the PCFDev Instance Server error, status code: 404, error code: 0 

### ISSUE THREAD

**Issue by chauhanr** [vmware-archive/pcfdev#129]
Hi I am trying to install PCF Dev 0.18 on CentOS7 server. I followed the following steps 
1. installed Virtual Box 5.1 
2. installed the CF CLI version 6.21.1+6fd3c9f-2016-08-10 
3. installed the plugin using cf cli - pcfdev-v0.18.0+PCF1.7.0-linux
4. started the pcf dev using   cf dev start 

The VM is downloaded successfully and the VM is provisioned as well as started with success. The final message on the console asks me to login to api.local.pcfdev.io using cf login -a command with --skip-ssl-validation option. 

But when I try to login I get the following error 

FAILED 
Server error, status code: 404, error code: 0, message:

When I do a curl -v api.local.pcfdev.io the output is the following: 

```
* About to connect() to api.local.pcfdev.io port 80 (#0)
*   Trying 192.8.245.17...
* Connected to api.local.pcfdev.io (192.xx.xxxx.17) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: api.local.pcfdev.io
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Location: https://api.local.pcfdev.io/
< Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 0
<
* Connection #0 to host api.local.pcfdev.io left intact
```

As I have understood from other issues is that the api.pcfdev.io must resolve to 192.168.11.11 but in my case it is resolving to 192.x.xxx.17. 

What could be the potential problem here. 

P.S - I also tried to force the api.local.pcfdev.io to be directed to 192.168.11.11 by adding an entry to the /etc/hosts file that changes the curl output 

```
* About to connect() to api.local.pcfdev.io port 80 (#0)
*   Trying 192.168.11.11...
* Connected to api.local.pcfdev.io (192.168.11.11) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: api.local.pcfdev.io
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 86
< Content-Type: application/json;charset=utf-8
< Date: Mon, 29 Aug 2016 07:26:49 GMT
< Server: nginx
< X-Cascade: pass
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: 55c8d39c-be93-432c-6d27-aef96f48bc75
< X-Vcap-Request-Id: 8a305a28-9f3f-4909-736c-c876718c6953::1458e6a2-c43c-4182-a6e4-d65eabc96801
<
{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
* Connection #0 to host api.local.pcfdev.io left intact
}
```

which is what is expected but when I try to login using the cf cli I keep getting the error mentioned above. 

```
FAILED 
Server error, status code: 404, error code: 0, message:
```

**Comment by mdelillo** [comment]
@chauhanr We actually have an Amazon Route53 entry that resolves `*.local.pcfdev.io` to `192.168.11.11`. The signs that you're describing indicate that something is getting in the way of you getting the correct dns resolution from AWS services. We suggest talking to your system administrator about what entries are being stored in your DNS nameservers. You can try running `dig api.local.pcfdev.io` to see what IP it resolves to and what server is doing the resolution.

As for the entry in `/etc/hosts` not working, that may be because there are multiple domains that need to resolve to `192.168.11.11` (`api.local.pcfdev.io`, `uaa.local.pcfdev.io`, etc.). You could try using something like dnsmasq which allows you to resolve `*.local.pcfdev.io` to `192.168.11.11`.

**Comment by chauhanr** [comment]
@mdelillo  Thanks for pointing us to the right direction. The dnsmasq entry did the trick. I am now able to login into the instance and work with it. Thanks for such a quick turn around. 

Ritesh
