### ISSUE TITLE
need commercial release info

### ISSUE THREAD

**Issue by shouah** [vmware-archive/pcfdev#137]
In the commercial version provided by Pivotal, how can we determine which OVA file correspond to which PCF version? there isn't any release notes or info posted with new OVA files published for download.

For instance you noted that your pcfdev 0.19.0 release notes that OVA version 0.234.0 corresponds to PCF 1.7.12, but is there a way to know if any of the other OVA published in the commercial download site correspond to which recent PCF releases?

Or can you update the commercial download page to document that information when a new OVA file posted correspond to a particular PCF release?

**Comment by sclevine** [comment]
Hi @shouah,

The only supported OVAs in the `internal` release on PivNet are those that correspond to published releases of PCF Dev. We do not publish PCF Dev CLI plugins that are able to download and start any of the unsupported OVAs.

The release is called "internal" because OVAs in that release are considered experimental build artifacts until they are tested and a CLI plugin is released to consume them. In fact, OVAs in that release may have a collection of PCF components that do not correspond to **any** PCF release, and they may not work at all. We don't consider this an issue because `cf dev start` will not download unsupported OVAs, and `cf dev import` will refuse to start unsupported OVAs.

**Comment by shouah** [comment]
Can you share roadmap information?

Specifically of interest the release rate for pcf-dev vs. pcf, meaning how often should we expect pcf-dev to be updated to catch up / match up with pcf release?

**Comment by sclevine** [comment]
We aim to release a version of PCF Dev for each major or minor PCF release as soon as that PCF release is cut. For instance, when PCF 1.8 is released, we plan to release PCF Dev 0.20.0 with PCF 1.8 components on the same day (or very shortly after).

PCF patch releases generally consist of CVE fixes that are often not applicable to PCF Dev (which runs on your local workstation, and isn't designed to run apps in production). If there are significant changes in a PCF patch release that are applicable to PCF Dev, we will generally cut a PCF Dev release with those changes as well. For example, PCF Dev 0.19.0 uses PCF 1.7.12 components because PCF 1.7.12 contained changes to support Spring Data Flow.

**Comment by shouah** [comment]
thank you for clarifying: I incorrectly expected frequent update to pcf-dev to match up with minor release of pcf.
