### ISSUE TITLE
time gets out of sync

### ISSUE THREAD

**Issue by pmuellr** [vmware-archive/pcfdev#148]
I believe I've noticed that if I leave PCF dev up all day, I end up getting some clock drift in the the code running there. Eg,  `cf ssh`'d into one of my apps and it was 10 minutes behind.  Which explained why the `make` invocations in my buildpack were complaining about "files from the future" or what-not.

Is this a known issue?  Maybe sometime simple to configure in VBox?

Not really sure how to debug this further, but am willing to answer any questions I have about my current set up; namely, latest PCF dev on Mac Yosemite, everything's been working like a champ (which is **sooo awesome - thank you for PCF dev!**)

**Comment by sclevine** [comment]
What version of PCF Dev are you running? We've switched back and forth between the `kvm-clocksource` and the `tsc-clocksource` in the kernel. The `kvm-clocksource` used in 0.19.0 seemed to cause CPU lockups.

**Comment by pmuellr** [comment]
```
$ cf dev version
PCF Dev version 0.20.0 (CLI: 54fb957, OVA: 0.317.0)
```

I first install PCF Dev last week, maybe week before.  Then saw it was updated recently, so did the update.  Honestly don't know if I saw the time drift in the previous version, I've only been leaving it up all day for the last few days ...

**Comment by sclevine** [comment]
Seems like `tsc` might not be the best choice: https://liquidat.wordpress.com/2013/04/02/howto-fixing-unstable-clocksource-in-virtualised-centos/

**Comment by kdvolder** [comment]
We've run into something like this. The clock on the pcf dev VM got 19 hours behind real time! This causes problems for us (Spring Tool Suite) because some calls to the cf-java-client are validating JWT access tokens on the client side. The tokens look expired on the client side and this causes errors making the cloudfoundry support in STS break completely (user can't connect to any pcf dev targets at all while its out of sync).

Apparantly, the cause of this large clock drift is caused by putting the host machine to sleep (i.e. close the lid of your laptop) while pcf dev is running.

It would be good if pcf dev could somehow sync up the clock properly when host machine is woken from sleep.

In the mean time we (STS) will probably implement a workaround, showing a hint to our users to 'Please restart pcf dev, its clock appears to be out of sync', whenever we see 'JWT token expired' type errors from PCF dev instance.

**Comment by dhrapson** [comment]
I'm seeing this also. PCF Dev version 0.28.0 (CLI: 5cda315, OVA: 0.547.0)

Deployments failures using nodejs_buidpack v1.6.10:

2017-11-09T13:47:11.97+0000 [CELL/0]     ERR Copying into the container failed: stream-in: nstar: error streaming in: exit status 2. Output: tar: ./app/src/stylesheets/_pui-variables.scss: time stamp 2017-11-09 14:37:34 is 3025.570497636 s in the future

I think I'm using the same workaround: cf dev stop && cf dev start.
Its inconvenient though because this has a multi-minute turnaround.

**Comment by aemengo** [comment]
This issue has already been resolved. Please upgrade to the latest version of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev).
