### ISSUE TITLE
Accessing pcfdev from another machine

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#160]
I've been using pcfdev on my Macbook (16GB) so far without any issues, but lately I've added other VMs such as - Artifactory, Concourse CI & MongoDB. 
All these virtual machines are competing for limited amount of RAM, and using pcfdev with Spring Cloud Services doubled the RAM config requirements. 
At times my laptop grinds to halt and my Java IDE becomes unresponsive as there is no RAM left for normal OS tasks and is heavily swapping memory in the background.

I tried moving my pcfdev environment to my desktop which has plenty of free RAM and much more CPU horsepower, whilst keeping my dev environment with other Vagrant machines intact on my Macbook.

The issue I've is - 
How do I bind my desktop's SSL port 443 to pcfdev's 192.168.11.11:443? 
So running cf commands on my Macbook are executing on pcfdev running on my desktop.
example-

> cf login -a https://10.1.xx.y --skip-ssl-validation

I tried VirtualBox port forwarding option, but it seems to forward the request onwards to pcfdev with my desktop IP address. The error message i get is

> 404 Not Found: Requested route ('10.1.xx.y') does not exist.'

Also, tried various other options - using NGINX and squid web proxy - none of them worked out of the box with minimal config tweak.

Please let me know if this is a valid configuration in which I can use pcfdev?
It will accelerate my CloudFoundry and Spring Cloud learning process a lot.

Kind Regards

**Comment by amitoj** [comment]
Sorry - duplicate

**Comment by vivekranjan** [comment]
Could you please add the link to the duplicate post here? I have the same problem and I could not find the solution. 

Thanks

**Comment by sclevine** [comment]
This was partially addressed in #161. On the connecting workstation, the PCF Dev system domain must resolve to the host that the PCF Dev VM is bound to. One simple way to do this is to configure dnsmasq on the connecting workstation to make *.local.pcfdev.io resolve to the IP of the host running the PCF Dev VM (instead of 192.168.11.11). You can use Virtualbox port forwarding to bind ports on the PCF Dev VM to that host.

Note that PCF Dev is not a secure distribution of PCF. You should not allow connections to PCF Dev from untrusted hosts. Configuring PCF Dev for non-local access is not officially supported.
