### ISSUE TITLE
PCF Dev support for Windows Hyper-V

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#168]
Installing 'Docker for Windows' has resulted in an unexpected side effect - it requires Windows Hyper-V feature on, which has a direct impact on Virtualbox. This has something to do with the hardware VT-x not visible to Virtualbox when Hyper-V is switched on. 
More and more of my development environment is based around docker and cannot think of an alternative other than not using Virtualbox.
Vagrant comes with Hyper-V support, which I haven't tried though, but eventually might have to.

So I'm requesting that please consider Hyper-V virtualisation in your near future releases.

**Comment by sclevine** [comment]
Hi @amitoj,

Thanks for the feature request.

The vast majority of our OS X users are able to take advantage of OS X native virtualization, while the majority of our Windows users are unable to take advantage of Hyper-V. While we hope to support Hyper-V at some point in the future, it will likely be after we support OS X native virtualization and various cloud platforms.

In the meantime, you can use Docker Machine (which is still available in Docker for Windows) with Virtualbox instead of Hyper-V if you need to run Docker and PCF Dev at the same time. I understand that Docker in Virtualbox is not quite as smooth an experience as Docker in Hyper-V, and I apologize if this is inconvenient.

**Comment by denghauseremc** [comment]
+1

**Comment by kamkie** [comment]
+1

**Comment by bfarrelly** [comment]
+1

**Comment by brandonh6k-old** [comment]
+1

**Comment by sergey-morenets** [comment]
+1

**Comment by adriangonsalves** [comment]
+1

**Comment by adminnz** [comment]
Over a year now.... any progress on this or are Windows developers second class customers?

**Comment by sclevine** [comment]
Hi @adminnz & @sergey-morenets,

The latest official release of PCF Dev provides the same feature set and (Virtualbox-based) experience for macOS, Windows 7-10, and Linux. We have put more effort into supporting Windows than macOS or Linux, due to the differences between Windows 7, 8, and 10.

I understand that Windows 10 has limitations that prevent Hyper-V and Virtualbox from running simultaneously, and that this causes friction when PCF Dev is used with Docker for Windows. This is one reason why support for Hyper-V continues to be a priority on our roadmap.

We recently started re-writing PCF Dev from scratch on top of the native hypervisors (xhyve/Hypervisor.Framework on Mac, Hyper-V on Windows, and KVM on Linux) along with a fully-functional BOSH director. The first publicly available alpha releases of this re-write will be for macOS exclusively, but we intend to release full support for Hyper-V on Windows shortly after that.

I am re-opening this issue for increased visibility.

**Comment by cesnek** [comment]
+1

**Comment by romuloreis** [comment]
+1

**Comment by kamkie** [comment]
I think this is now tracked at [cfdev](https://github.com/cloudfoundry-incubator/cfdev/issues/22)

**Comment by aemengo** [comment]
The latest iteration of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev) takes advantage of native virtualization - including Hyper-V on any Windows 10+ machine.
