### ISSUE TITLE
Certificate signed by unknown authority - MAC OSX

### ISSUE THREAD

**Issue by jcunhafonte** [vmware-archive/pcfdev#170]
Hi guys

When I try to run `cf dev start` I get this result:

> FAILED
> Error: failed to reach Pivotal Network: Post [...] x509: certificate signed by unknown authority.

I am using macOS Sierra

Thank you

**Comment by sclevine** [comment]
The domain `network.pivotal.io` is signed by a valid, well-known root certificate authority. Can you confirm that you are able to validate that domain using curl?

```
$ curl -v https://network.pivotal.io
```

**Comment by jcunhafonte** [comment]
Thank you for your response 👍 

No. I am not able to validate that domain using curl.

**Comment by aemengo** [comment]
Hello @jcunhafonte As noted before, `network.pivotal.io` has a valid certificate. The fact that you are unable to validate it implies that something is wrong with your environment. Please check that your system time is correct so that it does not assume that the cert is expired already. Otherwise, as a last resort, you can manually insert the certificate into your keychain as way to continue using the PCF Dev Cli.

![screen shot 2016-11-18 at 9 00 24 am](https://cloud.githubusercontent.com/assets/4236888/20432584/e5d09088-ad6d-11e6-964c-dc0cf0d64009.png)

Closing because this is not an issue intrinsic to PCF Dev.
