### ISSUE TITLE
Non-offline buildpacks are downloaded again and again

### ISSUE THREAD

**Issue by ghost** [vmware-archive/pcfdev#247]
When multiple apps are deployed using the same buildpack (e.g. https://github.com/cloudfoundry/java-buildpack.git#v4.2) then the buildpack is downloaded again and again for each application.
Isn't it possible to cache online-buildpacks? Buildpacks don't change, but apps are deployed often.
This slows down deployments extremely.

Is there a plan to
- implement caching for online-buildpacks?
- provide v4 java offline buildpacks?

Thanks for your help!

**Comment by sclevine** [comment]
Hi @christianschaible,

> Is there a plan to implement caching for online-buildpacks?

You can use `cf create-buildpack` to upload a buildpack to PCF Dev so that it doesn't need to be downloaded during each stage. (Assuming by "online-buildpacks" you mean buildpack URLs. The online/offline property actually has to do with whether buildpack dependencies, like Java, are downloaded each time. Buildpack URLs can point to buildpacks that are online or offline.)

> Is there a plan to provide v4 java offline buildpacks?

The buildpacks in PCF Dev are matched to the buildpacks in PCF.

> Isn't it possible to cache online-buildpacks?

Assuming you mean "cache buildpack URLs," no. We shouldn't assume that the buildpack bits available at a particular URL stay the same.
