### ISSUE TITLE
pcf dev _very_ slow to start

### ISSUE THREAD

**Issue by cowinr** [vmware-archive/pcfdev#282]
I'm running cf 6.34.0, pcf dev 0.28 on a Windows 7 PC with 8GB RAM.
I've used all the defaults following https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev/introduction
When I run `cf dev start` it takes 45 minutes to start up.
Unfortunately this is unusable, even as a trial to get familiar with PCF.

```
$ date
Sun, Jan 14, 2018  1:18:05 PM

$ cf dev start
Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
10 out of 58 running
17 out of 58 running
28 out of 58 running
35 out of 58 running
46 out of 58 running
58 out of 58 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://apps.local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

$ date
Sun, Jan 14, 2018  2:02:58 PM
```

**Comment by sclevine** [comment]
PCF Dev requires at least 4GB of system memory, and the start process is somewhat CPU and disk I/O intensive. While `cf dev start` usually takes ~15 minutes on modern hardware with 16 GB of total memory, it doesn't surprise me that it would take much longer to start on a machine with 8 GB of memory that was shipped with Windows 7.

As a workaround, you may be able to `cf dev suspend` the VM after it is booted, so that you don't have to wait for the VM to provision every time. It's also worth noting that starting a VM that was stopped with `cf dev stop` can actually take longer than provisioning a fresh VM after running `cf dev destroy`.

**Comment by cowinr** [comment]
OK, thanks for the info. It might be worth putting a note on the getting started guides to indicate you might have to wait 'several' minutes for the VM to provision?

**Comment by kdvolder** [comment]
I've been waiting close to an hour and my machine has 32Gb of memory.

**Comment by kdvolder** [comment]
After an hour wait it failed:

```
kdvolder@dellicioso:~$ date && cf dev start && date
Wed Feb 20 16:10:08 PST 2019
Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
29 out of 58 running
38 out of 58 running
48 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().
```

**Comment by aemengo** [comment]
@kdvolder You're using an outdated version of the CF Dev cli. Please upgrade:

```
$ cf uninstall-plugin cfdev
$ cf install-plugin -r "CF-Community" cfdev
$ cf dev version
CLI: 0.0.13

**Comment by kdvolder** [comment]
Tried. But this happens:

```
$ cf uninstall-plugin cfdev
Plugin cfdev does not exist.
FAILED
```

Checking version of cf dev I have:

```
$ cf dev version
$ cf dev version
PCF Dev version 0.30.0 (CLI: 850ae45, OVA: 0.549.0)
```

Version 0.30.0 is newer than 0.0.13? At least it is a higher number isn't it?

**Comment by kdvolder** [comment]
I figured the name of the plugin is actually 'pcfdev' so unistalled that. Then...

```
$ cf install-plugin -r "CF-Community" cfdev
Searching CF-Community for plugin cfdev...
Plugin requested has no binary available for your platform.
FAILED
```

So what now? (platform is Linux, Ubuntu 18.04 BTW).

Strange thing is the version 0.30.0 I had before was working fine until not too long ago when it seemed to be getting slower and slower starting up. I have since done a few rounds of `cf dev destroy` to try and clear that up, but problem only seems to be getting worse.

**Comment by aemengo** [comment]
@kdvolder Very sorry about that. version `0.30.0` stopped working recently because the self-signed certificates inside the VM image expired. You can better track that issue here: https://github.com/pivotal-cf/pcfdev/issues/365

As of right now, linux support is not yet available but is actively being worked on.

**Comment by kdvolder** [comment]
Okay thanks for the info. Unfortunately that means I don't have any practical way to do testing for some of the stuff I'm working on. So I hope there will be a solution for this soon.

BTW: If the version of pcf dev is indeed old, then there is a problem with instructions for setting it up here: https://docs.pivotal.io/pcf-dev/install-linux.html
