### ISSUE TITLE
pcfdev startup issue

### ISSUE THREAD

**Issue by neugn** [vmware-archive/pcfdev#319]
I just downloaded pcfdev 0.29 and tried to run 'cf dev start' and it fails after I enter by Pivotal Network email.  The reason indicated - invalid password. 

---------------------------------------------------------------------------------------------
neugn@mach1>cf dev version
PCF Dev version 0.29.0 (CLI: 49405ec, OVA: 0.548.0)

neugn@mach1>cf version
cf.exe version 6.35.2+88a03e995.2018-03-15

neugn@mach1>cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email> k*****@w****.com
FAILED
Error: invalid password.
---------------------------------------------------------------------------------------------

I can successfully login to my Pivotal network account at network.pivotal.io, as well as via 'cf login'

**Comment by sclevine** [comment]
Hi @neugn,

Sorry for the delay!

You can download the OVA from PivNet manually by following these steps:
1. Sign into PivNet in a browser
2. Navigate to the PCF Dev product
3. Select the "internal" release
4. Download OVA version 0.548.0
5. Run `cf dev import <path-to-OVA>`
6. Run `cf dev start`

**Comment by zenghao123456** [comment]
it doesnot work

cf dev import C:\Users\zenghao\.pcfdev\ova\pcfdev-v0.548.0.ova
NAME:
   dev - Control PCF Dev VMs running on your workstation

ALIAS:
   pcfdev

USAGE:
   cf dev SUBCOMMAND

SUBCOMMANDS:
   start                    Start the PCF Dev VM. When creating a VM, http proxy env vars are respected.
      [-m memory-in-mb]     Memory to allocate for VM. Default: half of system memory, no more than 4 GB.
      [-c number-of-cores]  Number of processor cores used by VM. Default: number of physical cores.
   stop                     Shutdown the PCF Dev VM. All data is preserved.
   suspend                  Save the current state of the PCF Dev VM to disk and then stop the VM.
   resume                   Resume PCF Dev VM from suspended state.
   destroy                  Delete the PCF Dev VM. All data is destroyed.
   status                   Query for the status of the PCF Dev VM.



because ，i use the pcfdev-v0.17.0+PCF1.7.0-windows

**Comment by sclevine** [comment]
@zenghao123456 `cf dev import` is only available in recent versions of PCF Dev. Also, all versions before v0.29.0 contain an expired certificate that prevents them from starting.

 Additionally, only a single OVA version works with each cf CLI plugin version.
