### ISSUE TITLE
Can not dowload PCF-dev from Pivotal network

### ISSUE THREAD

**Issue by longvhdeveloper** [vmware-archive/pcfdev#334]
I tried download pcfdev from Pivotal network and receive message : "Unfortunately, we are unable to provide you with access to download software at this time. Please contact export@pivotal.io for assistance."

I also tried send email to export@pivotal.io but not have rely. How I contact to download ?

**Comment by acsujea** [comment]
Same issue here for downloading PCF dev. When will this issue get resolved?

**Comment by sclevine** [comment]
Hi @acsujea,

This issue is specific to your individual  PivNet user account and affects all downloads from PivNet, not just PCF Dev. Please reach out to export@pivotal.io to determine if this access restriction can be lifted for your user.

Apologies for the trouble.

Alternatively, you could use [CF Dev](https://github.com/cloudfoundry-incubator/cfdev), which recent releases of PCF Dev are based on.
