### ISSUE TITLE
Unable to start PCF Dev, error at adding dvd drive cfdev-efi.iso

### ISSUE THREAD

**Issue by coderookie1994** [vmware-archive/pcfdev#347]
I have downloaded the latest PCF Dev image from the website and installed PCF Dev 0.0.9 plugin.
On trying to start the VM, I get the following error
![new bitmap image 4](https://user-images.githubusercontent.com/15284156/45383745-b4eac800-b629-11e8-9edd-20533db80087.jpg)

cf version is 6.38.0+7ddf0aadd.2018-08-07
Total system memory 8.0GB Windows 10 with Hyper-V

**Comment by aemengo** [comment]
@coderookie1994 Unfortunately, you're running into a bug that has slipped into the previous release. Since `$HOME` has a space `'  '` in the path, the value has to be escaped accordingly (which we weren't doing). We apologize for this and will have this resolved with our next release.

For now, you can use the `$env:CFDEV_HOME` environment variable as a workaround to point the state directory to different path on your filesystem.

```
$ cf dev stop # to clean any leftover resources
$ $env:CFDEV_HOME="C:\cfdev"
$ cf dev start -f E:\pcfdev-pas.v.2.0.20.0-build.0.82.0.iso
```

**Comment by coderookie1994** [comment]
Thank you @aemengo , changing the directory helped.
