### ISSUE TITLE
Error starting PCF Dev

### ISSUE THREAD

**Issue by ghost** [vmware-archive/pcfdev#362]
Hi guys!

I'm trying to deploy PCF Dev on my laptop using the last version available on Pivotal Network (pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz), but after many attemps I could not get it running.

I'm trying to run it using the following command on an Administrator PowerShell: 
```
cf dev start -f .\pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz -s scs -m 10240
```

And my laptop has these characteristics:

- 16 GB RAM (12 GB available on steady state).
- Intel Core i5-6440HQ @ 2.60 GHz (4 cores) (14-16% used on steady state).
- Windows 10.
- 342 GB of hard disk available before downloading the TGZ image.
- High performance battery saving settings, with CPU at 100% usage and hard drive shutdown disabled. I'm using the laptop to browse the Internet, check the mail and other non-resource consuming tasks, so it does not suspend or hibernate.

Everything seems to be fine until Spring Cloud Services are being deployed, having a failure which can be seen in the logs attached (it seems to be a problem when deploying RabbitMQ Server):

[log.zip](https://github.com/pivotal-cf/pcfdev/files/2808387/log.zip)

Normally this happens after 6 minutes deploying these services, having spent approximately 20 minutes in all the prior tasks. I've also tested with the default memory (8 GB), running a "cf dev stop" between tests to leave everything cleaned, and in both cases the failure is the same and the timing is also pretty similar, maybe with 30 seconds or 1 minute of variation.

Please, can you check what is happening with the deployment?

Thanks and regards!

**Comment by ghost** [comment]
Just for clarification, if I try to deploy PCF Dev without Spring Cloud Services everything works perfectly. It's only when trying to use them when I have problems.

**Comment by aemengo** [comment]
@ecristobal `Spring Cloud Services` is an expensive set of services to run on a laptop machine. Could you please try the same configuration and start command on a full desktop machine and see if that yields better results?

**Comment by ghost** [comment]
@aemengo unfortunately I can't because I don't have a desktop machine with enough resources to make the test. Anyway, as I saw in https://github.com/cloudfoundry-incubator/cfdev/issues/66, it seems that it's not a matter of being a laptop or not, but it's more related with the power of the machine. Also, due to our requirements it should run on a laptop because we must ensure mobility.

One option that could be feasible is to get a MacBook Pro laptop upgraded with 16GB of RAM, which has an Intel Core i5-8259U @ 2.30GHz processor, which performs almost twice better than the one in which the test was made. ¿Will it work on this machine?

**Comment by aemengo** [comment]
@ecristobal I cannot make any official claims with regards to laptop performance because we test and tune the product on desktop environments. But here are the specs of the last Macbook Pro laptop that we have successfully performed a PCF Dev start with `Spring Cloud Services` on:

<img width="698" alt="screen shot 2019-01-31 at 9 17 43 am" src="https://user-images.githubusercontent.com/4236888/52061088-91bea780-253b-11e9-96f7-d766dbfc726f.png">

In my personal experience, a common culprit of failure to start is the disk. Not just disk space but **disk speed** and this because of the amount disk I/O that the start process undergoes. If you suspect that your windows machine has a slow HDD and you find it cheaper or more viable to improve that, you could also give that a shot.

We'd very much appreciate if you kept us updated on your results.

**Comment by ghost** [comment]
@aemengo thanks for yor information!

Just for clarification, which were the RAM settings used to start PCF Dev on the aforementioned Macbook Pro? Were you using the default settings (8 GB), or have you configured more RAM to make it work?

I ask you this because the Macbook Pro option suits well for us, but we don't want to spend more money than needed, so we prefer a 13" model with 16 GB of RAM instead of the 15" model, which is more expensive. If PCF Dev needs less than 10GB to power on we think that it will work without any problem having also a STS running, as in previous PCF Dev versions we could make them run on a mid-2014 Macbook Pro with 16 GB of RAM (it was not very fast and reliant, but we could make it run some times). So, please, can you tell me the memory configuration of PCF Dev used in your test?

Thanks!

**Comment by aemengo** [comment]
@ecristobal These concerns come up often enough that I really wanted to do a more thorough assessment. I tried spinning up CF Dev with `scs` on a Macbook that resembles your specifications and here are my findings. With the following 15' Macbook Pro '2014 (16GB RAM):

<img width="621" alt="screen shot 2019-02-01 at 10 08 33 am" src="https://user-images.githubusercontent.com/4236888/52137343-5219bd80-2618-11e9-8f68-fa5aec0638a2.png">

For 3 times (default memory, default memory, and with `-m 10240`):
1. cf dev start `-s scs -f ....`
2. `cf create-service` on all three spring cloud services 
3. `cf push` 1 small application, bind a service

The startup was successful all three times. I found that the total RAM consumption clocked in between **6.6GB - 7.0GB**. Given that the default memory allocation is **8GB**, I feel like the numbers are too close for comfort. So, although it did start I would recommend at least `-m 10240` for serious development. Moreover, mininal programs were running on the laptop that was being testing on. Depending on what else is running in your case, it'd be _much safer_ to opt for a 32GB machine if possible. 

Finally, I just want to emphasize how important the disk is. I've seen much more successful startups on macs simply because they ship with reasonable SSDs, while there's much more variation on the Windows side of things.  

Memory analysis was done using the [htop](https://hisham.hm/htop/) utility. Hope this helps. As always, we're always trying to reduce the footprint of CF Dev
