### ISSUE TITLE
DELL ECS with PCFDEV

### ISSUE THREAD

**Issue by sikosi** [vmware-archive/pcfdev#381]
Hello!
This is a follow up of question I asked and got a response, however, there was no reply to my subsequent comment, hence I am creating a new Issue...
I have the newest CF Dev Version and trying to deploy the DELL ECS Service Broker. I have installed the BOSH CLI and checked BOSH link for deploaments, but I can't see or I don't understand where or how to use the Director to deploy the service Broker. Could you elaborate a little please, with may be a sample service broker deployment using BOSH?
Thank you sir!

**Comment by aemengo** [comment]
Your previous Github issue was closed because this is not the correct portal to instruct on getting acquainted with the BOSH ecosystem. Your question is neither the type of issues we deal with here nor is it CF Dev specific.

Perhaps you might have better luck on their community slack:
#bosh on https://slack.cloudfoundry.org
