### ISSUE TITLE
Adding own bosh-releases to MicroPCF, and e.g.: diego-release?

### ISSUE THREAD

**Issue by SamuelMarks** [vmware-archive/pcfdev#39]
How do I add my own bosh-releases to MicroPCF?

Would be handy for sharing internal development environments around, and updating CF to the latest development (or stable, e.g.: v231) version.

Thanks for all suggestions

PS: Yes I have seen https://github.com/pivotal-cf/micropcf/blob/master/DEVELOP.md

**Comment by abh1kg** [comment]
I was about to ask the same question before I stumbled upon this. I would like to know about this too

**Comment by sclevine** [comment]
Hi @SamuelMarks,

You cannot build an official version of PCF Dev (that includes services brokers) using this repo. However, you can fork this repo and modify its contents to build a version of PCF Dev that includes the Elastic Runtime along with your own BOSH-deployed components.

@mdelillo, could you explain what changes are now necessary to add new BOSH releases?

**Comment by abh1kg** [comment]
Hi @mdelillo , @sclevine ,
First off, I must say pcf-dev is really cool thing for developers. 
Can you please share the steps to add new BOSH releases to pcf-dev? 

Thanks

**Comment by mdelillo** [comment]
@SamuelMarks @abhikco the bosh releases used by PCF Dev are specified in the `versions.json` file in the root of the repo. We [compile](https://bosh.io/docs/compiled-releases.html) each bosh release and provide a URL to the resulting tgz on S3. If you want to add a release that exists on your local filesystem, you can use `path` instead of `url`. For example:

```
[
  {
    "name" : "cf",
    "url" : "s3://pcfdev/compiled-releases/cf-v235-1-ge9635da.tgz"
  },
  ...
  {
    "name" : "my-bosh-release",
    "path" : "/path/to/my-bosh-release"
  }
]
```

You then need to edit `images/manifest.yml`. Add your new release to the `releases` array, your release jobs to `jobs.templates`, and your job properties to `properties`. Then you should be able to build PCF Dev using `images/build`.

**Comment by SamuelMarks** [comment]
@mdelillo Hmm, so is there any real advantage to this approach, when compared with adding bosh-releases to the relevant files within [bosh-lite/packer](https://github.com/cloudfoundry/bosh-lite/tree/master/packer)?

**Comment by sclevine** [comment]
The advantage to our approach is that you don't need to spin up a BOSH director on the VM and deploy all the CF services to individual containers at runtime. (That's what people use BOSH-lite for.)

While it might be possible to do a BOSH deploy of CF to a BOSH-lite VM and packer-ize the result, the added complexity and resource consumption of that approach was less than ideal when I tried it. There's no reason to think that it wouldn't be possible to do this, but it's not the approach we're taking.
