### ISSUE TITLE
Can't download PCF Dev from Pivotal Network

### ISSUE THREAD

**Issue by daveburnsLIT** [vmware-archive/pcfdev#64]
I get 

**UNABLE TO DOWNLOAD**
_Unfortunately, we are unable to provide you with access to download software at this time. Please contact export@pivotal.io for assistance._

When trying to download latest version (pcfdev-v0.15.0.zip) of PCF Dev from the [pivotal network](https://network.pivotal.io/products/pcfdev). 

Also tried hitting the API download [link](https://network.pivotal.io/api/v2/products/pcfdev/releases/1710/product_files/4460/downl), but it gives 

{
status: 404,
message: "no API endpoint matches 'products/pcfdev/releases/1710/product_files/4460/download'"
}

**Comment by Turbots** [comment]
Indeed, both versions 0.14 and 0.15 appear to be down, according to the 404 emitted by the REST API

It has always worked for me before, so it is probably temporary.

**Comment by mdelillo** [comment]
Hi @daveburnsLIT,

That first message you are seeing means that your account is currently not allowed to download software from Pivotal Network. You'll have to reach out to export@pivotal.io and ask them to give you access.

The 404 you are getting is because you are clicking the link which is making a get request. You need to make a POST request as shown in the [Download API](https://network.pivotal.io/docs/file_download_api#public/docs/api/v2/download.md).

**Comment by daveburnsLIT** [comment]
Thanks Mark, didn't realize I needed special permissions for the download

**Comment by sclevine** [comment]
In general, you don't need special permissions to download PCF Dev. Your account was flagged -- likely inadvertently. Don't hesitate to contact export@pivotal.io as Mark mentioned.
