### ISSUE TITLE
Support for other Vagrant providers

### ISSUE THREAD

**Issue by brentpabst** [vmware-archive/pcfdev#72]
Can we get additional packer boxes for other vagrant providers?

It's be nice to run this on VMWare, AWS, or Hyper-V.

**Comment by sclevine** [comment]
We are moving away from using Vagrant to distribute PCF Dev. The next release will use a cf CLI plugin to start PCF Dev in Virtualbox, and that plugin will eventually be extended to support other virtualization providers (AWS in the short term, vSphere and native hypervisors in the long term).

That said, we've had enough interest in AWS that the next release will also include a Vagrant box for AWS. Please try it out when we release it and let us know if you have any feedback! :smile:

**Comment by acdha** [comment]
@sclevine Any chance of official Docker images? The beta.docker.com Mac & Windows apps offer good UX and use the native hypervisor on each OS so you don't have to deal with Virtualbox.

**Comment by sclevine** [comment]
The Docker Beta requires Windows 10 or OS X 10.10, and many of our users are not running those yet. I put together a build of this a while ago [here](https://github.com/sclevine/nanocf), but we could not think of a compelling reason to distribute PCF Dev as a Docker image as opposed to an OVA.

We do have long term plans to allow our cf CLI plugin to take advantage of native hypervisors instead of Virtualbox if your system supports them.
