### ISSUE TITLE
cf install-plugin pcfdev-v0.16.0-osx reports zero version

### ISSUE THREAD

**Issue by Zteve** [vmware-archive/pcfdev#76]
After `cf install-plugin pcfdev-v0.16.0-osx` we receive the message `Plugin pcfdev v0.0.0 successfully installed.` which is incorrect, or misleading.

**Comment by sclevine** [comment]
Hi @Zteve,

Thanks for reporting this. We are aware of the issue. It's difficult for us to configure this correctly due to the way our pipeline promotes release candidates (ex. 0.16.1-rc.1) to releases (ex. 0.17.0 or 0.16.1).

I'll leave this issue open for now.

-Stephen

**Comment by sclevine** [comment]
The recommended method for installing PCF Dev has changed. Instead of running `cf install-plugin`, you can now run the plugin binary directly to install it. This suppresses the confusing `Plugin pcfdev v0.0.0 successfully installed.` message.

We're still working on a way to get the right version number into the plugin, but I'm closing this issue for now.
