### ISSUE TITLE
Failure to handle 'paused' VM state

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [vmware-archive/pcfdev#78]
When working with pcfdev version 0.16.0 on OSX, we get the following error:

```
FAILED
Error: failed to handle VM state 'paused'
```

For all commands listed in `cf dev help`, with a slightly different output for destroy:

```
Destroying VM...
FAILED
Error: failed to destroy VM: failed to handle VM state 'paused'
```

**Comment by MarkyMarkMcDonald** [comment]
After killing a bunch of ssh sessions into the box running pcfdev, we were able to run `pcf dev destroy` successfully from the box itself. Not sure how to reproduce this, please feel free to close if it's not helpful.

**Comment by sclevine** [comment]
Hi @MarkyMarkMcDonald,

This is a known issue -- if the VM gets into an unexpected state, `cf dev destroy` can't destroy it.
Also, we use "saved" state instead of "paused" state to suspend VMs, when we should consider VMs in either state to be suspended (and recoverable with `cf dev resume`).

This will be fixed in the next release.

Thanks for the report,
Stephen
