### ISSUE TITLE
pcfdev box has issue connecting to broker running on another machine

### ISSUE THREAD

**Issue by betht1220** [vmware-archive/pcfdev#81]
I have a broker running with pcf-dev, and have created a postgres service instance. The app is bound to the postgres service instance. However, the application has error (followed)
Caused by: org.postgresql.util.PSQLException: Connection to 192.168.150.40:32773 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

I’m able to use db client to connect to 192.168.150.40:32773. So it seems the pcfdev box is having problem communicating with an external VM ie 192.168.150.40.

I tried to login to the pcfdev box, but do not have the credentials.

Any tips?

Thanks

**Comment by sclevine** [comment]
Hi Beth,

You need to add a security group to permit your app to make connections to your external DB service. By default, apps can only make connections to public IP addresses, the VM, and the host. See [here](https://github.com/pivotal-cf/pcfdev/blob/master/FAQ.md#container-to-external) for instructions. In your case, this should look something like:

```
cf create-security-group db <(echo '[{"protocol":"all","destination":"192.168.150.40"}]')
cf bind-running-security-group db
cf restart your-app
```

You can login to the VM to test connectivity with `ssh vcap@ssh.local.pcfdev.io` (password: `vcap`). However, you may want to test connectivity from an app container (using `cf ssh your-app`) instead of the VM itself.

Hope this help!
Stephen

**Comment by betht1220** [comment]
Stephen
   Your suggestion solves the problem.  My micro-services are deployed and running. Mucho thanks.
-Beth
