### ISSUE TITLE
Does pcfdev support Routing API?

### ISSUE THREAD

**Issue by frozzygoh** [vmware-archive/pcfdev#83]
Hi,

I am trying to have my CF app to listen to multiple custom ports by creating multiple routes. 

I have a few questions regarding the the pcfdev v0.16.0 which can be obtained from here: 
https://network.pivotal.io/products/pcfdev

1) What is the CF API version tied to the pcfdev?
2) Is routing API enabled on the pcfdev?
3) If no, how can we enable the routing API on the pcfdev?

Thank you.

**Comment by sclevine** [comment]
Hi @frozzygoh,

Component version are available in the [release notes](https://github.com/pivotal-cf/pcfdev/releases). PCF Dev 0.16.0 includes CF v235.

The routing API is not included in PCF Dev 0.16.0 because it is not enabled in PCF 1.7.0. There is no way to enable it, because the `routing-api` job is not present on the VM. You could attempt to build your own PCF Dev with routing-api using this repo, or wait until we make a release that includes it.

Thanks,
Stephen

**Comment by frozzygoh** [comment]
Hi Stephen,

Thank you so much for the prompt response! Do you have any recommendations on any existing VM available which already has the routing-api present, or any VM or endpoint that has a CF API version 2.53.0+ (seems only from this version onwards routing ?

As far as I have tried to research, I only found we could try BOSH-LITE, and some extra procedure to enable the routing API.

**Comment by sclevine** [comment]
Hi @frozzygoh,

You could deploy CF to BOSH-lite until a release of PCF Dev has the components you need. See [here](https://bosh.io/docs/bosh-lite.html).

**Comment by frozzygoh** [comment]
Ok, thanks a lot @sclevine! Have a good day. :+1:

**Comment by iggymoran** [comment]
PCF Dev is currently at version 0.19.0.

Are there any plans on enabling the routing API anytime soon?

**Comment by sclevine** [comment]
@iggymoran @frozzygoh Routing API and TCP routing will be available in 0.20.0, which should be released very soon.

**Comment by iggymoran** [comment]
@sclevine, does this mean we'll also get the ability to create tcp routes?
